### ISSUE TITLE
Consider using `BitFaster.Caching`

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.MnemonicDB#30]
I saw that some parts of the code has in-memory caching using `ConcurrentDictionary`, [`BitFaster.Caching`](https://github.com/bitfaster/BitFaster.Caching) provides [`ConcurrentLru`](https://github.com/bitfaster/BitFaster.Caching/wiki/ConcurrentLru) and [`ConcurrentLfu`](https://github.com/bitfaster/BitFaster.Caching/wiki/ConcurrentLfu) primitives as [Caches](https://github.com/bitfaster/BitFaster.Caching/wiki/Caches) that might yield better performance (needs to be benchmarked).

**Comment by halgari** [comment]
Ended up going a different route with caching and caches are now immutable internally so updates to the DB don't require reloading the entire cache
