### ISSUE TITLE
Use `global` for imports

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.MnemonicDB#69]
Source generators should use `global::` when referencing anything because it prevents ambiguity:

```csharp
namespace Foo.Bar;

using Bar.Baz;
```

In this example, the `using Bar.Baz` will try to resolve to `Foo.Bar.Baz` instead of `Bar.Baz`. Adding a `global::` will resolve this issue:

```csharp
namespace Foo.Bar;

using global::Bar.Baz;
```

**Comment by halgari** [comment]
this is fixed in main
