### ISSUE TITLE
Silent null exception for arrays

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.MnemonicDB#92]
https://github.com/Nexus-Mods/NexusMods.MnemonicDB/blob/54bba268c2abede4c4f21d601317c7d1999e8f71/src/NexusMods.MnemonicDB.SourceGenerator/ModelAnalyzer.cs#L270

`IArrayTypeSymbol` doesn't implement `INamedTypeSymbol`, `highLevel` will be set to `null` and we'll ignore that fact, resulting in a null exception further down the line.

To repro, make an attribute where either of the type arguments are arrays:

```csharp
public partial class MyModelArrayTest : IModelDefinition
{
    public static readonly MyAttribute MyAttribute = new("MyNamespace", nameof(MyAttribute));
}

public class MyAttribute(string ns, string name) : ScalarAttribute<int[], int>(ValueTags.Blob, ns, name)
{
    protected override int ToLowLevel(int[] value)
    {
        throw new NotImplementedException();
    }
}
```

Instead of suppressing null checks, it'd be better to either have explicit exceptions or at least `Debug.Assert`. The best way is still handling null values.

**Comment by halgari** [comment]
I'm not sure that we want to support a scalar array, I'm not sure that is trying to be accomplished here. For byte arrays we have blobs, and for other types of array-like things we have tuples or separate attributes. If this is a dimention like thing, such as a `Vector2f` then we can support that natively, or back it as a blob

**Comment by erri120** [comment]
> I'm not sure that we want to support a scalar array, I'm not sure that is trying to be accomplished here. For byte arrays we have blobs, and for other types of array-like things we have tuples or separate attributes. If this is a dimention like thing, such as a `Vector2f` then we can support that natively, or back it as a blob

`HashedBlobAttribute<byte[]>` doesn't work because of this.

**Comment by halgari** [comment]
Ah I see, makes sense
